<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StackDev</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <!-- Permite correr en un runtime más nuevo (por ejemplo .NET 10) si no tienes el 8 -->
    <RollForward>Major</RollForward>
  </PropertyGroup>

</Project>
